export enum NotificationType{
  JOB_REQUEST="JOB_REQUEST",
  NEW_FOLLOWER="NEW_FOLLOWER",
  REQUEST_STATUS_CHANGE_PROVIDER="REQUEST_STATUS_CHANGE_PROVIDER",
  REQUEST_STATUS_CHANGE_USER="REQUEST_STATUS_CHANGE_USER"
}
