export enum NotificationType{
  JOB_REQUEST="JOB_REQUEST",
  NEW_FOLLOWER="NEW_FOLLOWER",
  REQUEST_STATUS_CHANGE_PROVIDER="REQUEST_STATUS_CHANGE_PROVIDER",
  REQUEST_STATUS_CHANGE_USER_ACCEPTED="REQUEST_STATUS_CHANGE_USER_ACCEPTED",
  REQUEST_STATUS_CHANGE_USER_REJECTED="REQUEST_STATUS_CHANGE_USER_REJECTED",
  REQUEST_STATUS_CHANGE_USER_FINISHED="REQUEST_STATUS_CHANGE_USER_FINISHED",
}
