package ar.edu.itba.paw.models.user.notification;

public enum NotificationType {
    JOB_REQUEST,
    NEW_FOLLOWER,
    REQUEST_STATUS_CHANGE_PROVIDER,
    REQUEST_STATUS_CHANGE_USER_ACCEPTED,
    REQUEST_STATUS_CHANGE_USER_REJECTED,
    REQUEST_STATUS_CHANGE_USER_FINISHED,
}
